LIBNAME = libmidi

include $(SRC_DIR)/rules.mk

CXXFLAGS += -I./ \
		    -I$(FREERTOS_KERNEL_SRC_DIR)/include \
		    -I$(FREERTOS_PORTABLE_SRC_DIR) \
			-I$(FATFS_SRC_DIR) \
			-I$(HASH_SRC_DIR) \
			-I$(SRC_DIR)/include \
			$(APP_DEFS) \
			$(HARDWARE_DEFS) \
			$(FREERTOS_DEFS) \
        	-I$(KLIBC_SRC_DIR) \
        	-I$(TLSF_SRC_DIR) \
        	-I$(FATFS_SRC_DIR) \
		    -I$(CONSOLE_SRC_DIR) \
		    -I$(CONSOLE_HANDLERS_SRC_DIR) \
		    -I$(READLINE_SRC_DIR) \
		    -I$(FREERTOS_KERNEL_SRC_DIR)/include \
		    -I$(FREERTOS_PORTABLE_SRC_DIR) \
		    -I$(MMGR_SRC_DIR) \
            -I$(KLEN_INLINED_SRC_DIR) \
            -I$(LIBOPENCM3_SRC_DIR) \
            -I$(LED_SRC_DIR) \
            -I$(HASH_SRC_DIR) \
            -I$(DEVICES_SRC_DIR) \
            -I$(SRC_DIR)/libstorage \
            -I$(SRC_DIR)/libmidi \
			$(APP_DEFS) \
			$(HARDWARE_DEFS) \
			$(FREERTOS_DEFS) \
			$(MEM_POOLS_DEFS)



