LIBNAME = libstorage

include $(SRC_DIR)/rules.mk

CXXFLAGS += -I./ \
	-I$(SRC_DIR)/include \
	-I$(FATFS_SRC_DIR) \
	-I$(KLEN_INLINED_SRC_DIR) \
	-I$(LIBOPENCM3_SRC_DIR)
#	-I$(STM32_SD_HAL_SRC_DIR)
#	-I$(LIBOPENCM3_SRC_DIR) 
